let a = Number(5);
let b = Number(-1);
let c = Number("Hello");
let d = String(55);
let e = String(-10);
let f = String(0);
document.writeln(a);
document.writeln(b);
document.writeln(c);
document.writeln(d);
document.writeln(e);
document.writeln(f);